ettaselnasel/sites/users_bp/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from sites.users_bp.forms import SignupForm, LoginForm, UpdateProfileForm, UpdatePasswordForm, RequestResetForm, ResetPasswordForm, SellerSetupForm
from sites import db
from sites.models import User, Product
from flask_login import login_user, current_user, logout_user, login_required
from sites.helpers import save_picture, delete_picture, send_email, send_sms

users_bp = Blueprint('users', __name__) 


@users_bp.route('/signup', methods=['GET', 'POST'])
def signup():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = SignupForm()
    
    if request.method == 'POST' and form.validate_on_submit():
        user = User(
            fullname=form.fullname.data,
            username=form.username.data,
            email_or_phone=form.email_or_phone.data,  # استقبال رقم الهاتف أو البريد
            password=form.password.data
        )
        
        # إضافة المستخدم لقاعدة البيانات
        db.session.add(user)
        db.session.commit()

        # إرسال البريد الإلكتروني أو رسالة SMS بناءً على المدخل
        if '@' in user.email_or_phone:  # إذا كان بريد إلكتروني
            send_email(user, condition="confirm_email")
        else:
            pass# إذا كان رقم هاتف
            #send_sms(user, condition="confirm_phone")
        
        flash("تم إنشاء الحساب بنجاح. يرجى التحقق من بريدك الإلكتروني أو رقم هاتفك لتأكيد الحساب.", 'success')
        logout_user()  # تسجيل خروج المستخدم بعد التسجيل
        return redirect(url_for('users.activation_info'))
    
    return render_template('signup.html', title="إنشاء حساب", form=form)

@users_bp.route('/activation-info', methods=['GET'])
def activation_info():
    return render_template('activation_info.html', title="تأكيد البريد الإلكتروني")

# تأكيد البريد الإلكتروني
@users_bp.route('/confirm-email/<token>')
def confirm_email(token):
    user = User.verify_confirm_email_token(token)
    if user is None:
        flash('رابط التفعيل غير صالح أو منتهي الصلاحية.', 'danger')
        return redirect(url_for('users.signup'))
    
    if user.is_confirmed:
        flash('بريدك الإلكتروني قد تم تأكيده مسبقًا.', 'info')
    else:
        user.is_confirmed = True
        db.session.commit()
        login_user(user, remember=True)
        flash('تم تأكيد بريدك الإلكتروني بنجاح! اختر دورك الآن.', 'success')
        return redirect(url_for('users.choose_role'))

# تأكيد رقم الهاتف
@users_bp.route('/confirm-phone/<token>')
def confirm_phone(token):
    user = User.verify_confirm_phone_token(token)
    if user is None:
        flash('رابط التفعيل غير صالح أو منتهي الصلاحية.', 'danger')
        return redirect(url_for('users.signup'))
    
    if user.is_confirmed:
        flash('رقم هاتفك قد تم تأكيده مسبقًا.', 'info')
    else:
        user.is_confirmed = True
        db.session.commit()
        flash('تم تأكيد رقم هاتفك بنجاح!', 'success')
    
    return redirect(url_for('main.home'))

@users_bp.route('/resend-confirmation', methods=['GET'])
def resend_confirmation():
    if not current_user.is_authenticated:
        return redirect(url_for('users.login'))
    
    if not current_user.is_confirmed:
        if '@' in current_user.email_or_phone:
            send_email(current_user, condition="confirm_email")
        else :
            pass
            #send_sms(current_user, condition="confirm_phone")
        flash('تمت إعادة إرسال رسالة تأكيد البريد الإلكتروني أو رسالة تفعيل رقم الهاتف بنجاح.', 'info')
    else:
        flash('حسابك مفعل بالفعل.', 'info')
    
    return redirect(url_for('users.activation_info'))

@users_bp.route('/setup-seller', methods=['GET', 'POST'])
def setup_seller():
    if not current_user.is_authenticated or not current_user.is_confirmed:
        return redirect(url_for('users.login'))

    form = SellerSetupForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            current_user.store_name = form.store_name.data
            current_user.store_location = form.store_location.data
            current_user.store_phone_number = form.phone_number.data
            current_user.product_description = form.product_description.data
            current_user.user_type = 'seller'
            db.session.commit()
            flash('تم تحديث معلومات متجرك بنجاح!', 'success')
            return redirect(url_for('main.home'))

    return render_template('setup_seller.html', title="إعداد التاجر", form=form)

@users_bp.route('/choose-role', methods=['GET', 'POST'])
def choose_role():
    if not current_user.is_authenticated:
        return redirect(url_for('users.login'))

    if request.method == 'POST':
        role = request.form.get('role')
        if role == 'customer':
            return redirect(url_for('main.home'))
        elif role == 'seller':
            return redirect(url_for('users.setup_seller'))
        else:
            flash('يرجى اختيار دور صحيح.', 'danger')

    return render_template('choose_role.html', title="اختر دورك")

@users_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            user = User.query.filter_by(email_or_phone=form.email_or_phone.data).first()
            if user and form.password.data == user.password:  # تحقق من كلمة المرور (يفضل استخدام hash للتحقق)
                if user.is_confirmed:
                    login_user(user, remember=form.remember.data)
                    next_page = request.args.get('next')
                    flash("لقد تم تسجيل دخولك بنجاح", 'success')
                    return redirect(next_page) if next_page else redirect(url_for('main.home'))
                else:
                    flash('هذا البريد الإلكتروني غير مفعل. يرجى تأكيد بريدك الإلكتروني أو رقم هاتفك.', 'warning')
                    return redirect(url_for('users.login'))
            else:
                flash('توجد مشكلة في إدخال البيانات، يرجى المحاولة مرة أخرى.', 'danger')
    return render_template('login.html', title="تسجيل الدخول", form=form)

@users_bp.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users_bp.route('/dashboard', methods=['GET'])
@login_required
def dashboard():
    products = Product.query.filter_by(author=current_user).all()
    return render_template('dashboard.html', title="لوحة التحكم", active_tab='dashboard', products=products)


@users_bp.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    form = UpdateProfileForm()
    password_form = UpdatePasswordForm()

    if form.validate_on_submit():
        if form.image.data:
            if current_user.image_file != 'default_user.jpg':
                delete_picture(current_user.image_file, "static/profile_pics")
            picture_file = save_picture(form.image.data, path='static/profile_pics', output_size=(200, 200))
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email_or_phone = form.email_or_phone.data
        db.session.commit()
        flash('تم تحديث ملفك الشخصي بنجاح!', 'success')
        return redirect(url_for('users.profile'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email_or_phone.data = current_user.email_or_phone
    else:
        flash('توجد مشكلة في إدخال البيانات، يرجى المحاولة مرة أخرى.', 'danger')
        form.username.data = current_user.username
        form.email_or_phone.data = current_user.email_or_phone

    if password_form.validate_on_submit():
        if current_user.password == password_form.current_password.data:
            current_user.password = password_form.new_password.data
            db.session.commit()
            flash('تم تغيير كلمة المرور بنجاح!', 'success')
            return redirect(url_for('users.profile'))
        else:
            flash('كلمة المرور الحالية غير صحيحة', 'danger')

    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('profile.html', title='الملف الشخصي',
                           image_file=image_file, form=form, password_form=password_form, active_tab='profile')
    
@users_bp.route("/reset_password", methods=["GET", "POST"])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email_or_phone=form.email_or_phone.data).first()
        if user:
            send_email(user=user, condition="reset_email")
        flash(
            "إذا كان هذا الحساب موجودًا، فسوف تتلقى بريدًا إلكترونيًا يحتوي على التعليمات",
            "info",
        )
        return redirect(url_for("users.login"))
    return render_template("reset_request.html", title="اعادة ضبط كلمة المرور", form=form)


@users_bp.route("/reset_password/<token>", methods=["GET", "POST"])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    user = User.verify_pw_reset_token(token)
    if not user:
        flash("The token is invalid or expired", "warning")
        return redirect(url_for("users.reset_request"))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        user.password = form.new_password.data
        db.session.commit()
        flash(f"تم تحديث كلمة المرور الخاصة بك. يمكنك الآن تسجيل الدخول", "success")
        return redirect(url_for("users.login"))
    return render_template("reset_password.html", title="اعادة ضبط كلمة المرور", form=form)

ettaselnasel/sites/templates/activation_info.html
{% extends "layout.html" %}
{% block content %}
<section class="activation-info-section">
    <div class="container">
        <h1>تأكيد البريد الإلكتروني</h1>
        <p>تهانينا! لقد تم إنشاء حسابك بنجاح.</p>
        <p>لإكمال عملية التسجيل، يرجى التحقق من بريدك الإلكتروني وتأكيد حسابك عبر الرابط المرسل إليك. إذا لم تتلقَ رسالة التأكيد، يرجى اتباع الإرشادات التالية:</p>

        <h2>إرشادات التحقق</h2>
        <ul>
            <li><strong>التحقق من مجلد الرسائل غير المرغوب فيها (Spam/Junk):</strong> قد تكون رسالة التفعيل قد وصلت إلى مجلد الرسائل غير المرغوب فيها. تأكد من التحقق من هذا المجلد.</li>
            <li><strong>التأكد من صحة عنوان البريد الإلكتروني:</strong> تأكد من أنك أدخلت عنوان البريد الإلكتروني الصحيح عند التسجيل.</li>
            <li><strong>انتظار بضع دقائق:</strong> قد يستغرق الأمر بضع دقائق حتى تتلقى رسالة التفعيل. يرجى الانتظار لبعض الوقت.</li>
            <li><strong>إعادة إرسال رسالة التفعيل:</strong> إذا لم تتلقَ الرسالة بعد فترة طويلة، يمكنك <a href="{{ url_for('users.resend_confirmation') }}">إعادة إرسال رسالة التفعيل</a>.</li>
        </ul>

        <h2>المساعدة والدعم</h2>
        <p>إذا كنت تواجه أي مشاكل في تأكيد بريدك الإلكتروني أو لديك أي استفسارات، لا تتردد في الاتصال بفريق الدعم لدينا:</p>
        <ul>
            <li><strong>البريد الإلكتروني للدعم:</strong> info.ettaselnasel@gmail.com</li>
            <li><strong>رقم الهاتف:</strong> +1234567890</li>
            <li><strong>الدردشة المباشرة:</strong> <a href="{{url_for('main.contact')}}">ابدأ دردشة</a></li>
        </ul>

        <h2>هل تحتاج إلى مساعدة إضافية؟</h2>
        <p>للحصول على مزيد من المساعدة، يمكنك زيارة قسم الأسئلة الشائعة (FAQ) على موقعنا أو الاطلاع على <a href="#">دليل المستخدم</a>.</p>

        <a href="{{ url_for('users.login') }}" class="cta-button">تسجيل الدخول</a>
    </div>
</section>
{% endblock content %}

ettaselnasel/sites/templates/confirm_email_message.html
<!DOCTYPE html>
<html>
<head>
    <style>
        .button {
            background-color: #4CAF50;
            color: #fff;
            padding: 10px 20px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 10px 2px;
            cursor: pointer;
        }
    </style>
</head>
<body>
    <h2>تأكيد بريدك الإلكتروني</h2>
    <p>شكرًا لإنشاء حساب لدينا. لتفعيل حسابك، يرجى النقر على الرابط أدناه:</p>
    <a href="{{ confirm_url }}" class="button">تأكيد بريدك الإلكتروني</a>
</body>
</html>

ettaselnasel/sites/templates/create_product.html
{% extends "control_board.html" %}

{% block control_board_content %}
<div class="create-product-container">
    <h1 class="create-product-title">إنشاء منتج جديد</h1>
    {{ ckeditor.load() }}

    <form method="POST" action="{{ url_for('products.create_product') }}" enctype="multipart/form-data">
        {{ product_form.hidden_tag() }}
        <input type="hidden" name="form_name" value="product_form">

        <!-- حقل العنوان -->
        <div class="form-group">
            {{ product_form.title.label(class="form-label") }}
            {% if product_form.title.errors %}
            {{ product_form.title(class="is-invalid") }}
            <div class="invalid-feedback">
                {% for error in product_form.title.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %}
            {{ product_form.title(class="form-input") }}
            {% endif %}
        </div>

        <!-- حقل التصنيف -->
        <div class="form-group">
            {{ product_form.category.label(class="form-label") }}
            {% if product_form.category.errors %}
            {{ product_form.category(class="is-invalid") }}
            <div class="invalid-feedback">
                {% for error in product_form.category.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %}
            {{ product_form.category(class="form-input") }}
            {% endif %}
        </div>

        <!-- زر إنشاء تصنيف جديد -->
        <button type="button" id="newCategoryBtn" class="submit-button">إنشاء تصنيف جديد</button>

        <!-- حقل الـ Slug -->
        <div class="form-group">
            {{ product_form.slug.label(class="form-label") }}
            {% if product_form.slug.errors %}
            {{ product_form.slug(class="is-invalid") }}
            <div class="invalid-feedback">
                {% for error in product_form.slug.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %}
            {{ product_form.slug(class="form-input") }}
            {% endif %}
        </div>

        <!-- حقل الصورة -->
        <div class="form-group">
            <div class="file-upload-wrapper">
                {{ product_form.icon(class="file-upload-input", id="customFile1") }}
                <label class="file-upload-label" for="customFile1">{{ product_form.icon.label.text }}</label>
            </div>
        </div>

        <!-- حقل المحتوى -->
        <div class="form-group">
            {{ product_form.content.label(class="form-label") }}
            {% if product_form.content.errors %}
            {{ product_form.content(class="is-invalid") }}
            <div class="invalid-feedback">
                {% for error in product_form.content.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %}
            {{ product_form.content(class="form-input") }}
            {% endif %}
        </div>

        <!-- حقل السعر -->
        <div class="form-group">
            {{ product_form.price.label(class="form-label") }}
            {% if product_form.price.errors %}
            {{ product_form.price(class="is-invalid", id="price_input") }}
            <div class="invalid-feedback">
                {% for error in product_form.price.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %}
            {{ product_form.price(class="num-input", id="price_input") }}
            {% endif %}
        </div>

        <!-- حقل الكمية -->
        <div class="form-group">
            {{ product_form.quantity.label(class="form-label") }}
            {% if product_form.quantity.errors %}
            {{ product_form.quantity(class="is-invalid") }}
            <div class="invalid-feedback">
                {% for error in product_form.quantity.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %}
            {{ product_form.quantity(class="num-input") }}
            {% endif %}
        </div>

        <!-- حقل التخفيض -->
        <div class="form-group">
            <div class="remember-me">
                {{ product_form.is_discount(id="is_discount_checkbox") }}
                <label for="{{ product_form.is_discount.id }}">{{ product_form.is_discount.label.text }}</label>
            </div>
        </div>

        <!-- حقل نسبة التخفيض -->
        <div class="form-group" id="discount_field" style="display: none;">
            {{ product_form.discount.label(class="form-label") }}
            {% if product_form.discount.errors %}
            {{ product_form.discount(class="is-invalid", id="discount_input") }}
            <div class="invalid-feedback">
                {% for error in product_form.discount.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %}
            {{ product_form.discount(class="num-input", id="discount_input") }}
            {% endif %}
        </div>

        <!-- حقل السعر النهائي (يتم إرساله عبر النموذج إلى Flask) -->
        <div class="form-group" id="final_price_field" style="display: none;">
            {{ product_form.final_price.label(class="form-label") }}
            {{ product_form.final_price(class="form-input final-price-input", id="final_price_input") }}
        </div>

        <!-- إضافة حقل مخفي لإرسال final_price مع البيانات إلى Flask -->
        <input type="hidden" id="final_price_hidden" name="final_price">

        <!-- زر الإرسال -->
        <div class="form-group form-group-c">
            {{ product_form.submit(class="submit-button") }}
        </div>
    </form>
</div>

<form method="POST" action="{{ url_for('products.create_product') }}" enctype="multipart/form-data">
    {{ category_form.hidden_tag() }}
    <input type="hidden" name="form_name" value="category_form">
    <div id="newCategoryModal" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <h2>إنشاء تصنيف جديد</h2>
            <div class="form-group">
                {{ category_form.category.label(class="form-label") }}
                {{ category_form.category(class="form-input") }}
                <div class="file-upload-wrapper">
                {{ category_form.icon(class="file-upload-input2", id="customFile2") }}
                <label class="file-upload-label" for="customFile2">{{ category_form.icon.label.text }}</label>
                </div>
            </div>
            <div class="form-group form-group-c">
                {{ category_form.submit(class="submit-button") }}
            </div>
        </div>
    </div>
</form>


<!-- JavaScript للتفاعل مع الحقول -->
<script>
   // كود JavaScript للتعامل مع النافذة المنبثقة
var modal = document.getElementById("newCategoryModal");
var btn = document.getElementById("newCategoryBtn");
var span = document.getElementsByClassName("close")[0];

btn.onclick = function() {
    modal.style.display = "block";
}

span.onclick = function() {
    modal.style.display = "none";
}

window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
}

document.getElementById("newCategoryForm").onsubmit = function(e) {
    e.preventDefault();
    var newCategory = document.getElementById("newCategory").value;
    // هنا يمكنك إضافة كود لإرسال التصنيف الجديد إلى الخادم
    console.log("تم إنشاء تصنيف جديد: " + newCategory);
    modal.style.display = "none";
    // يمكنك هنا تحديث قائمة التصنيفات في النموذج الرئيسي
}
document.getElementById("newCategoryForm").onsubmit = function(e) {
    e.preventDefault();
    var newCategory = document.getElementById("newCategory").value;
    // إرسال التصنيف الجديد
    this.submit();
}

document.querySelector("form[action='{{ url_for('products.create_product') }}']").onsubmit = function(e) {
    if (document.querySelector("input[name='form_name']").value === "product_form") {
        // إرسال المنتج الجديد
        this.submit();
    }
}
</script>


{% endblock %}

ettaselnasel/sites/templates/dashboard.html
{% extends "control_board.html" %}
{% block control_board_content %}
<div class="dashboard-container">
    {% if current_user.is_authenticated %}
        {% if current_user.user_type == 'seller' %}
        <h1 class="dashboard-title">لوحة التحكم</h1>
        <div class="dashboard-stats">
            <!-- الإحصائيات هنا -->
        </div>
        <div class="dashboard-stats">
            <div class="stat-card">
                <h3>إجمالي المبيعات</h3>
                <p class="stat-value">$10,500</p>
            </div>
            <div class="stat-card">
                <h3>عدد الطلبات</h3>
                <p class="stat-value">150</p>
            </div>
            <div class="stat-card">
                <h3>عدد المنتجات</h3>
                <p class="stat-value">75</p>
            </div>
            <div class="stat-card">
                <h3>عدد العملاء</h3>
                <p class="stat-value">500</p>
            </div>
        </div>
    
        <div class="dashboard-section">
            <h2>الطلبات الأخيرة</h2>
            <table class="dashboard-table">
                <thead>
                    <tr>
                        <th>رقم الطلب</th>
                        <th>العميل</th>
                        <th>التاريخ</th>
                        <th>الحالة</th>
                        <th>المبلغ</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>#1001</td>
                        <td>أحمد محمد</td>
                        <td>2024-08-05</td>
                        <td><span class="status-completed">مكتمل</span></td>
                        <td>$120</td>
                    </tr>
                    <tr>
                        <td>#1002</td>
                        <td>سارة علي</td>
                        <td>2024-08-06</td>
                        <td><span class="status-pending">قيد المعالجة</span></td>
                        <td>$85</td>
                    </tr>
                    <!-- يمكن إضافة المزيد من الصفوف هنا -->
                </tbody>
            </table>
        </div>
    
        <div class="dashboard-section">
            <h2>إدارة المنتجات</h2>
            <a href="{{ url_for('products.create_product') }}">
                <button class="add-product-btn">إنشاء منتج جديد</button>
            </a>
            <table class="dashboard-table">
                <thead>
                    <tr>
                        <th>اسم المنتج</th>
                        <th>السعر</th>
                        <th>الكمية</th>
                        <th>الحالة</th>
                        <th>الإجراءات</th>
                    </tr>
                </thead>
                <tbody>
                    {% for product in products %}
                    <tr>
                        <td>{{ product.title }}</td>
                        <td>${{ product.price }}</td>
                        <td>{{ product.quantity }}</td>
                        {% if product.quantity and product.quantity > 7 %}
                        <td><span class="status-instock">متوفر</span></td>
                        {% else %}
                        <td><span class="status-lowstock">كمية منخفضة</span></td>
                        {% endif %}
                        <td>
                            <a href="{{ url_for('products.edit_product', product_id=product.id, category_id=product.cat.id) }}"><button class="action-btn edit-btn">تعديل</button></a>
                            <button type="button" class="action-btn delete-btn"
                            data-product-id="{{ product.id }}"
                            data-category-id="{{ product.cat.id }}"
                            onclick="showDeleteModal(this)">حذف</button>
    
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% else %}
        <h1 class="dashboard-title">التحول الى تاجر</h1>
        <center>
            <a href="{{url_for('users.setup_seller')}}" class="cta-button">التحول الى تاجر</a>
        </center>
        {% endif %}
    {% endif %}
</div>

<!-- نافذة التأكيد للحذف -->
<div id="deleteProductModal" class="modal">
    <div class="modal-content">
        <span class="close">&times;</span>
        <p>هل أنت متأكد من أنك تريد حذف هذا المنتج؟</p>
        <button id="confirmDeleteBtn" class="confirm-delete-btn">تأكيد الحذف</button>
    </div>
</div>
<script>
    function showDeleteModal(button) {
        var modal = document.getElementById("deleteProductModal");
        var confirmBtn = document.getElementById("confirmDeleteBtn");
        var span = document.getElementsByClassName("close")[0];

        // Show the modal
        modal.style.display = "block";

        // Close modal when 'x' is clicked
        span.onclick = function() {
            modal.style.display = "none";
        };

        // Close modal when clicking outside of the modal
        window.onclick = function(event) {
            if (event.target == modal) {
                modal.style.display = "none";
            }
        };

        // Confirm deletion
        confirmBtn.onclick = function() {
            var productId = button.getAttribute("data-product-id");
            var categoryId = button.getAttribute("data-category-id");

            // Build the delete URL using the actual IDs
            var deleteUrl = `/product/${categoryId}/${productId}/delete`;

            // Redirect to the delete URL
            window.location.href = deleteUrl;
        };
    }

</script>
{% endblock %}

ettaselnasel/sites/templates/home.html
{% extends "layout.html" %}
{% block content %}
<section class="hero-section">
    <h1> مرحبا بكم في <span class="text-lightgreen">اتصل نصل</span></h1>
    <p>أفضل موقع تسوق للحصول على ما تريده بسهولة وسرعة</p>
    <a href="{{url_for('products.products')}}" class="cta-button">استكشف منتجاتنا</a>
</section>


<section class="products-section">
    <h2>عروض اليوم</h2>
    
<div class="product-list">
        {% for product in discount_products %}
    <a href="{{url_for('products.product_detail', category_id=product.cat.id, product_id=product.id)}}" class="link no-underline">
    <div class="product-card ">
    {% if product.is_discount %}
            <!-- عرض نسبة الخصم على البطاقة -->
            <div class="discount-badge">{{ product.discount }}%</div>
    {% endif %}
    <img src="{{url_for('static', filename='product_icons/'+product.icon)}}" alt="Product 1">
    <h3>{{product.title}}</h3>
    <p>{{product.slug}}</p>
    <p class="price">
        {% if product.is_discount %}
            <span class="old-price">${{ product.price }}</span> <!-- السعر الأصلي -->
        {% endif %}
        ${{product.final_price}} <!-- السعر بعد الخصم -->
    </p>
    <div class="author-info">
        <div class="author-img-container">
            <img class="author-img" src="{{url_for('static', filename='profile_pics/'+product.author.image_file)}}" alt="">
        </div>
        <div class="author-text">
            <span>By: <a href="#" class="">{{product.author.username}}</a></span>
        </div>
    </div>
    <button class="add-to-cart">أضف إلى السلة</button>
</div>
</a>
{% endfor %}
    </div>
</section>

<section class="hero-section">
    <h1>--------------------------</h1>
</section>

<section class="products-section">
        <h2>منتجاتنا</h2>
        <div class="product-list">
        {% for product in products %}
        <a href="{{url_for('products.product_detail', category_id=product.cat.id, product_id=product.id)}}" class="link no-underline">
        <div class="product-card ">
        {% if product.is_discount %}
            <!-- عرض نسبة الخصم على البطاقة -->
            <div class="discount-badge">{{ product.discount }}%</div>
        {% endif %}
        <img src="{{url_for('static', filename='product_icons/'+product.icon)}}" alt="Product 1">
        <h3>{{product.title}}</h3>
        <p>{{product.slug}}</p>
        <p class="price">
            {% if product.is_discount %}
                <span class="old-price">${{ product.price }}</span> <!-- السعر الأصلي -->
            {% endif %}
            ${{product.final_price}} <!-- السعر بعد الخصم -->
        </p>
        <div class="author-info">
            <div class="author-img-container">
                <img class="author-img" src="{{url_for('static', filename='profile_pics/'+product.author.image_file)}}" alt="">
            </div>
            <div class="author-text">
                <span>By: <a href="#" class="">{{product.author.username}}</a></span>
            </div>
        </div>
        <button class="add-to-cart">أضف إلى السلة</button>
    </div>
</a>
{% endfor %}
        </div>
</section>

<section class="hero-section">
    <a href="{{url_for('products.products')}}" class="cta-button">تصفح المزيد</a>
</section>
{% endblock content %}